### ISSUE TITLE
strategy: patch not working

### ISSUE THREAD

**Issue by Quezler** [rymndhng/release-on-push-action#10]
Just got into using github actions, but it seems my releases increment the minor instead of the patch, despite this file appearing to be configured properly? 

https://github.com/Quezler/mindustry__plugin--bomberman/blob/master/.github/workflows/github.yml

**Comment by rymndhng** [comment]
@Quezler can you try the latest version. I think I've pushed a fix in https://github.com/rymndhng/release-on-push-action/tree/v0.9.1

**Comment by Quezler** [comment]
looks like #11 will work just fine, i added both yesterday: https://github.com/Quezler/mindustry__plugin--bomberman/blob/827ae0a533bc247564f5ae13c353c01a2e70d77e/.github/workflows/github.yml (but i have since removed github workflows alltogether since i could not get both of them to work neatly together)
