### ISSUE TITLE
Commits in body since last release

### ISSUE THREAD

**Issue by Hjaltesorgenfrei** [rymndhng/release-on-push-action#15]
Could you add the possibility of adding the commits that have been added since last release to the body of the release?

**Comment by rymndhng** [comment]
That sounds like a reasonable feature. Do you have specific requirements for output format for each commit, would this work as a format?

```
- [SHA] [Commit Title]
```

Hypothetical body: 

# Changes
- fa15ae4 Fix dockerfile
- 907d0f0 Rewrite with Babashka (#16)

**Comment by rymndhng** [comment]
@Hjaltesorgenfrei It's implemented now. Check this out as an example: https://github.com/rymndhng/release-on-push-action/releases/tag/v0.12.0
