### ISSUE TITLE
clojure.lang.ExceptionInfo: Cannot run program "curl": error=7, Argument list too long [at line 107, column 3]

### ISSUE THREAD

**Issue by losisin** [rymndhng/release-on-push-action#23]
There is a bug when calling curl as json string with too long list of commits. [https://github.com/rymndhng/release-on-push-action/blob/master/src/release_on_push_action/core.clj#L107] Possible solution: https://unix.stackexchange.com/a/174355

**Comment by rymndhng** [comment]
Thanks for the bug report!

**Comment by rymndhng** [comment]
This should be solved in v0.12.1 now :)
