### ISSUE TITLE
Version is not incremented after placing `release:minor` or `release:patch` labels in pull request.

### ISSUE THREAD

**Issue by SiarheiTuzhykTR** [rymndhng/release-on-push-action#28]
Yesterday I created `0.0.1` and `0.1.0` versions in my repository. Then I created PR with a `release:minor` label. And after the merge into master version didn't change to `0.2.0`.  It still left as `0.1.0`. 

Today I've created a new PL with a `release:patch` label and GitHub Actions tried to create a `0.0.1` tag. 

![image](https://user-images.githubusercontent.com/60696995/78421608-ae83cd00-7661-11ea-9e19-ea0dab051143.png)

Could you please help with that?

**Comment by rymndhng** [comment]
Something to keep in mind with this Github Action is that it relies on the the Github Release, not the latest git tag. Keep in mind: A Github Release is a tag, but not all tags are releases.

If you do not have a first release created, you can hop on over to the `Releases` tab in your repository and select an existing tag to convert it into a release. 

Once you have that setup, you should be able to re-run the action and try it again.

See if that works for you!

**Comment by SiarheiTuzhykTR** [comment]
Yeah, that works. Thank you for your helping.

**Comment by nsisodiya** [comment]
I tried `release:minor` and it worked. but later on next few pull request, `release:patch` didn't worked.
I don't know why but overall, it seems unpredictable.

**Comment by rymndhng** [comment]
@nsisodiya that's a bummer! I'd be happy to help investigate & debug if you create a new issue for that, and can provide more reproduction steps (and/or job output).
