### ISSUE TITLE
The ability to add to the previous release doesn't seem to be working properly

### ISSUE THREAD

**Issue by shnskfjwr** [rymndhng/release-on-push-action#29]
Hello.

The current `rymndhng/release-on-push-action` is not working properly.

A `release:major` is set to a fixed release of `1.0.0`.
A `release:minor` is set to a fixed release of `0.1.0`.
A `release:patch` is set to a fixed release of `0.0.1`.

For example, if you release `release:minor` twice, the first time will work fine, but
After the second time, the following errors will occur.

```
Starting process...
Received context {:bump-version-scheme norelease, :token ***, :repo ****/****, :dry-run false, :sha *********}
Fetching related data...
Generating release...
Executing Release
 {
  "name" : "0.1.0",
  "tag_name" : "v0.1.0",
  "draft" : false,
  "prerelease" : true,
  "target_commitish" : "*************",
  "body" : "**********"
}
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "ready_exists",
      "field": "tag_name"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
}
```

The ability to add to the previous release doesn't seem to be working properly.

**Comment by shnskfjwr** [comment]
Resolved.

By editing the created release and unchecking the `This is a pre-release`, the second and subsequent release numbers were added.

If you do not do this, `Validation Failed` will be raised.

Is it possible to automatically uncheck the `This is a pre-release` for releases made with GithubActions?

**Comment by rymndhng** [comment]
Yes, and thanks for figuring it out yourself 😊! I will look into setting that option, and yes it is doable!

**Comment by rymndhng** [comment]
@shnskfjwr Can you check to see if this issue is solved now?

**Comment by shnskfjwr** [comment]
It worked! Thank you so much!
