### ISSUE TITLE
GitHub Organization Repository - HTTP 404

### ISSUE THREAD

**Issue by adecchi-2inno** [rymndhng/release-on-push-action#41]
Hi,
I am getting 404, when i tried to use internally in my github organization. I created a Personal Access Token with read and write permission.
`
 ----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  babashka.curl: status 404
Location: /var/src/release-on-push-action/src/release_on_push_action/github.clj:56:4

----- Context ------------------------------------------------------------------
52: (defn fetch-latest-release
53:   "See https://developer.github.com/v3/repos/releases/#get-the-latest-release"
54:   [context]
55:   (parse-response
56:    (curl/get
       ^--- babashka.curl: status 404
57:     (format "https://api.github.com/repos/%s/releases/latest" (:repo context))
58:     {:headers {"Authorization" (str "token " (:token context))}})))
`

**Comment by rymndhng** [comment]
Take a peek at https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token.

I'm uncertain about the specific grants as I've been using this with success (and others) by using the automatically generated `GITHUB_TOKEN`.

With a Personal Access Token, I believe you need to select all of the `repo` permissions.

**Comment by alexfornuto** [comment]
I encountered this same issue when using `@master`. Locking to the release as `rymndhng/release-on-push-action@v0.16.0` solved, so I guess there's something in `master` that's broken?

**Comment by rymndhng** [comment]
I don't have an organization setup, so I don't have an easily reproducible environment right now. I'll try to do a bit of digging sometime this week.

**Comment by rymndhng** [comment]
This is proving to be a bit more difficult that I expected to debug, and there are several things that may be at play:

For folks who have reported this bug, does your repository have an existing release?

I've noticed that the API will return a `404` when there is no initial release created. Is this the case for your projects? If so, I think I can improve the error handling and give guidance to seed an initial release via the Github UI.

I have also noticed that if you specify an invalid token, the API response will be a `401` instead, which leads me to believe it's not an issue with organizational tokens.

**Comment by lxwbr** [comment]
@rymndhng Can verify, running latest `master`, didn't have initial release, received a `404`. Created a first release manually, re-run the job, everything was fine then.

**Comment by mdcsaenz** [comment]
Getting the same error as well PR merged and attempted to run
` with:
    bump_version_scheme: minor
    tag_prefix: v
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name a33c1e8d386190de44885934e670421113c74_6c7de6 --label 8a33c1 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_BUMP_VERSION_SCHEME -e INPUT_TAG_PREFIX -e INPUT_RELEASE_BODY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kairos/kairos":"/github/workspace" 8a33c1:e8d386190de44885934e670421113c74
Starting process...
Received context ***:token ***, :repo afs-kairos/kairos, :sha 1eea5cd8c7a79f6bcdbc7989b623b3b2b58d592a, :input/release-body , :input/tag-prefix v, :bump-version-scheme minor, :dry-run false***
Fetching related data...
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  babashka.curl: status 404
Location: /var/src/release-on-push-action/src/release_on_push_action/github.clj:56:4

----- Context ------------------------------------------------------------------
52: (defn fetch-latest-release
53:   "See https://developer.github.com/v3/repos/releases/#get-the-latest-release"
54:   [context]
55:   (parse-response
56:    (curl/get
       ^--- babashka.curl: status 404
57:     (format "https://api.github.com/repos/%s/releases/latest" (:repo context))
58:     ***:headers ***"Authorization" (str "token " (:token context))***)))
59: 
60: ;; -- Github Commit API  -------------------------------------------------------
61: (defn fetch-commit

----- Locals -------------------------------------------------------------------
context: ***:token "***", :repo "afs-kairos/kairos", :sha "1eea5cd8c7a79f6bcdbc7989b623b3b2b58d592a", :input/release-body "", :input/tag-prefix "v", :bump-version-scheme "minor", :dry-run false***

----- Stack trace --------------------------------------------------------------
babashka.curl/get                                  - <built-in>
release-on-push-action.github/parse-response       - /var/src/release-on-push-action/src/release_on_push_action/github.clj:56:4
release-on-push-action.github/parse-response       - /var/src/release-on-push-action/src/release_on_push_action/github.clj:22:1
release-on-push-action.github/fetch-latest-release - /var/src/release-on-push-action/src/release_on_push_action/github.clj:55:3
release-on-push-action.github/fetch-latest-release - /var/src/release-on-push-action/src/release_on_push_action/github.clj:52:1
...
                                                   - <expr>:51:20
release-on-push-action.core/fetch-related-data     - /var/src/release-on-push-action/src/release_on_push_action/core.clj:48:1
release-on-push-action.core                        - /var/src/release-on-push-action/src/release_on_push_action/core.clj:136:22
clojure.core/apply                                 - <built-in>
user                                               - <expr>:1:52
`

I have all the repo perms for my github token as well. Ran master

**Comment by rymndhng** [comment]
Hey folks! This should be fixed on master now. Let me know if you have any issues with it :)
