### ISSUE TITLE
Feature Request: allow removing the "v".

### ISSUE THREAD

**Issue by alexfornuto** [rymndhng/release-on-push-action#42]
Thanks for this project! I'm trying to use it with an existing project that already has a naming convention that doesn't include "v" at in the version or tag number. If this could be a true/false flag, or perhaps even an option to use a custom string, I think that would be a nice improvement, and help adoption of the tool.

Thanks in advance!

**Comment by rymndhng** [comment]
Yeah, I think that seems like a reasonable thing to add. I would lean towards the custom string approach.

**Comment by rymndhng** [comment]
This is released now in `v0.17.0` 🎉
