### ISSUE TITLE
Used in Github Enterprise Server

### ISSUE THREAD

**Issue by ufo0531** [rymndhng/release-on-push-action#57]
I use this Github Action in Github Enterprise Server, but the API url seems to be a fixed value `https://api.github.com/`.
It will cause the response to be 401 when request to Github.
Can it be replace with a environment variable or else?

**Comment by rymndhng** [comment]
Hello!

It appears that there's already an environment variable `GITHUB_API_URL` available as an alternative to hardcoding api.github.com. [link](https://docs.github.com/en/actions/reference/environment-variables).

I can look into changing over to the environment variable in the next release.

**Comment by rymndhng** [comment]
@ufo0531 I've released `v0.22.0` which should support the Github Enterprise Server. Let me know if this works in an enterprise setup!

If this approach does not work, I can add support for a custom environment variable.

**Comment by ufo0531** [comment]
It seems OK now, thanks

**Comment by rymndhng** [comment]
Glad to hear it!
