### ISSUE TITLE
Is there anyway to set a release name that is different than the tag name?

### ISSUE THREAD

**Issue by kaush-13** [rymndhng/release-on-push-action#66]
For example if the tag is v1.0.1 but we want the release name to show as "Release 1.0.1".

**Comment by kaush-13** [comment]
I opened up a PR and tested the change off of my fork. Please let me know if you see any issues with adding this #67

**Comment by rymndhng** [comment]
This is available in v0.24.0 now.

Thank you for your PR. The implementation has changed slightly from your initial PR. See the example in README.md  👉 https://github.com/rymndhng/release-on-push-action#can-i-change-the-name-of-the-release

**Comment by kaush-13** [comment]
Thanks @rymndhng !!
