### ISSUE TITLE
Support for a `dry_run` input?

### ISSUE THREAD

**Issue by atra2396** [rymndhng/release-on-push-action#70]
Hi, first of thanks for this Action, it's almost exactly what I need. There is one (hopefully simple) feature that I would benefit from - having access to the `dry_run` flag as a part of the action. Skimming the code it looks like it already exists for the tests. In our case, there are occasions when we want to generate the next tag first, but not actually create a release until a few other criteria have been fulfilled. Currently we have to use a couple different Actions to achieve this, but if this Action had a `dry_run` flag which still output the next tag/release without actually creating it then we could simplify our workflow.

**Comment by rymndhng** [comment]
Hi @atra2396 -- Yeah that seems reasonable!
